#!/usr/bin/env bash

[[ -f reactive-amqp-importer/target/reactive-amqp-importer-0.0.1-SNAPSHOT.jar ]] || (cd reactive-amqp-importer; mvn package)
java -jar reactive-amqp-importer/target/reactive-amqp-importer-0.0.1-SNAPSHOT.jar $@
