logging.level:
  reactor: WARN
  com.pivotal.rabbitmq.importer: DEBUG

file-sender:
  queue: my-queue
  #uri: src/main/resources/small-wordcount.txt
  uri: https://raw.githubusercontent.com/MarcialRosales/rabbitmq-streaming-playground/master/reactive-amqp-importer/src/main/resources/wordcount.txt
